# Arquivo definindo valores do padrão MIDI

OITAVA_MINIMA = -2
OITAVA_MAXIMA = 8

VOLUME_MINIMO = 0
VOLUME_MAXIMO = 127

INSTRUMENTO_MINIMO = 0
INSTRUMENTO_MAXIMO = 127

# Definido no padrão midi
VALOR_MIDI_MAXIMO = 127

CODIGO_INSTRUMENTO_TELEFONE_TOCANDO = 125