# Arquivo definindo valores do padrão MIDI

OITAVA_MINIMA = -2
OITAVA_MAXIMA = 8

VOLUME_MINIMO = 0
VOLUME_MAXIMO = 127

INSTRUMENTO_MINIMO = 0
INSTRUMENTO_MAXIMO = 127

TOM_MINIMO = 0
TOM_MAXIMO = 127

NOTA_LA = 9
NOTA_SI = 11
NOTA_DO = 0
NOTA_RE = 2
NOTA_MI = 4
NOTA_FA = 5
NOTA_SOL = 7

CODIGO_INSTRUMENTO_TELEFONE_TOCANDO = 125